FROM golang:alpine3.19 AS builder

RUN apk update && apk add --no-cache git

WORKDIR /app

COPY *.mod *.sum ./
RUN go mod download

COPY . .
RUN rm -f application_aggregator_api

ENV CGO_ENABLED=0
RUN go build -a -o application_aggregator_api ./cmd/api/application_aggregator_api.go

FROM alpine:latest

RUN apk update && apk add --no-cache bash
WORKDIR /app
COPY --from=builder /app/application_aggregator_api /app/application_aggregator_api
CMD ["./application_aggregator_api"]