// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Swagger loan application aggregator service - OpenAPI 3.0
 *
 * This is a sample some LoanApplication aggregator
 *
 * API version: 1.0.0
 */

package openapi

import (
	"context"
	"net/http"
)



// LoanApplicationAPIRouter defines the required methods for binding the api requests to a responses for the LoanApplicationAPI
// The LoanApplicationAPIRouter implementation should parse necessary information from the http request,
// pass the data to a LoanApplicationAPIServicer to perform the required actions, then write the service results to the http response.
type LoanApplicationAPIRouter interface { 
	LoanApplication(http.ResponseWriter, *http.Request)
}


// LoanApplicationAPIServicer defines the api actions for the LoanApplicationAPI service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type LoanApplicationAPIServicer interface { 
	LoanApplication(context.Context, LoanApplication) (ImplResponse, error)
}
