// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Swagger loan application aggregator service - OpenAPI 3.0
 *
 * This is a sample some LoanApplication aggregator
 *
 * API version: 1.0.0
 */

package openapi

import (
	"context"
	"net/http"
)



// ConfigAPIRouter defines the required methods for binding the api requests to a responses for the ConfigAPI
// The ConfigAPIRouter implementation should parse necessary information from the http request,
// pass the data to a ConfigAPIServicer to perform the required actions, then write the service results to the http response.
type ConfigAPIRouter interface { 
	GetConfigs(http.ResponseWriter, *http.Request)
	CreateConfig(http.ResponseWriter, *http.Request)
	GetConfigByUUID(http.ResponseWriter, *http.Request)
	DeleteConfigByUUID(http.ResponseWriter, *http.Request)
	EditConfigByUUID(http.ResponseWriter, *http.Request)
	GetConfigByOrganizationUUID(http.ResponseWriter, *http.Request)
	DeleteConfigByOrganizationUUID(http.ResponseWriter, *http.Request)
	EditConfigByOrganizationUUID(http.ResponseWriter, *http.Request)
}
// LoanApplicationsAPIRouter defines the required methods for binding the api requests to a responses for the LoanApplicationsAPI
// The LoanApplicationsAPIRouter implementation should parse necessary information from the http request,
// pass the data to a LoanApplicationsAPIServicer to perform the required actions, then write the service results to the http response.
type LoanApplicationsAPIRouter interface { 
	LoanApplications(http.ResponseWriter, *http.Request)
	CreateLoanApplication(http.ResponseWriter, *http.Request)
	GetLoanApplicationByUUID(http.ResponseWriter, *http.Request)
	DeleteLoanApplicationByUUID(http.ResponseWriter, *http.Request)
	EditLoanApplicationByUUID(http.ResponseWriter, *http.Request)
}
// OrganizationsAPIRouter defines the required methods for binding the api requests to a responses for the OrganizationsAPI
// The OrganizationsAPIRouter implementation should parse necessary information from the http request,
// pass the data to a OrganizationsAPIServicer to perform the required actions, then write the service results to the http response.
type OrganizationsAPIRouter interface { 
	Organizations(http.ResponseWriter, *http.Request)
	CreateOrganization(http.ResponseWriter, *http.Request)
	GetOrganizationByUUID(http.ResponseWriter, *http.Request)
	DeleteOrganizationByUUID(http.ResponseWriter, *http.Request)
	EditOrganizationByUUID(http.ResponseWriter, *http.Request)
}


// ConfigAPIServicer defines the api actions for the ConfigAPI service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type ConfigAPIServicer interface { 
	GetConfigs(context.Context) (ImplResponse, error)
	CreateConfig(context.Context, Config) (ImplResponse, error)
	GetConfigByUUID(context.Context, string) (ImplResponse, error)
	DeleteConfigByUUID(context.Context, string) (ImplResponse, error)
	EditConfigByUUID(context.Context, string, Config) (ImplResponse, error)
	GetConfigByOrganizationUUID(context.Context, string) (ImplResponse, error)
	DeleteConfigByOrganizationUUID(context.Context, string) (ImplResponse, error)
	EditConfigByOrganizationUUID(context.Context, string, Config) (ImplResponse, error)
}


// LoanApplicationsAPIServicer defines the api actions for the LoanApplicationsAPI service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type LoanApplicationsAPIServicer interface { 
	LoanApplications(context.Context) (ImplResponse, error)
	CreateLoanApplication(context.Context, LoanApplication) (ImplResponse, error)
	GetLoanApplicationByUUID(context.Context, string) (ImplResponse, error)
	DeleteLoanApplicationByUUID(context.Context, string) (ImplResponse, error)
	EditLoanApplicationByUUID(context.Context, string, LoanApplication) (ImplResponse, error)
}


// OrganizationsAPIServicer defines the api actions for the OrganizationsAPI service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type OrganizationsAPIServicer interface { 
	Organizations(context.Context) (ImplResponse, error)
	CreateOrganization(context.Context, Organization) (ImplResponse, error)
	GetOrganizationByUUID(context.Context, string) (ImplResponse, error)
	DeleteOrganizationByUUID(context.Context, string) (ImplResponse, error)
	EditOrganizationByUUID(context.Context, string, Organization) (ImplResponse, error)
}
