// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Swagger loan application aggregator service - OpenAPI 3.0
 *
 * This is a sample some LoanApplication aggregator
 *
 * API version: 1.0.0
 */

package openapi

import (
	"context"
	"errors"
	"net/http"
)

// ConfigAPIService is a service that implements the logic for the ConfigAPIServicer
// This service should implement the business logic for every endpoint for the ConfigAPI API.
// Include any external packages or services that will be required by this service.
type ConfigAPIService struct {
}

// NewConfigAPIService creates a default api service
func NewConfigAPIService() *ConfigAPIService {
	return &ConfigAPIService{}
}

// GetConfigs - get configs
func (s *ConfigAPIService) GetConfigs(ctx context.Context) (ImplResponse, error) {
	// TODO - update GetConfigs with the required logic for this service method.
	// Add api_config_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, []Config{}) or use other options such as http.Ok ...
	// return Response(200, []Config{}), nil

	// TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	// return Response(404, nil),nil

	// TODO: Uncomment the next line to return response Response(500, {}) or use other options such as http.Ok ...
	// return Response(500, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetConfigs method not implemented")
}

// CreateOrganization - create new config
func (s *ConfigAPIService) CreateOrganization(ctx context.Context, config Config) (ImplResponse, error) {
	// TODO - update CreateOrganization with the required logic for this service method.
	// Add api_config_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(201, Config{}) or use other options such as http.Ok ...
	// return Response(201, Config{}), nil

	// TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	// return Response(400, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("CreateOrganization method not implemented")
}

// GetConfigById - get config data
func (s *ConfigAPIService) GetConfigById(ctx context.Context, id int32) (ImplResponse, error) {
	// TODO - update GetConfigById with the required logic for this service method.
	// Add api_config_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, Config{}) or use other options such as http.Ok ...
	// return Response(200, Config{}), nil

	// TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	// return Response(404, nil),nil

	// TODO: Uncomment the next line to return response Response(500, {}) or use other options such as http.Ok ...
	// return Response(500, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetConfigById method not implemented")
}

// DeleteConfigById - Delete config data
func (s *ConfigAPIService) DeleteConfigById(ctx context.Context, id int32) (ImplResponse, error) {
	// TODO - update DeleteConfigById with the required logic for this service method.
	// Add api_config_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, {}) or use other options such as http.Ok ...
	// return Response(200, nil),nil

	// TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	// return Response(404, nil),nil

	// TODO: Uncomment the next line to return response Response(500, {}) or use other options such as http.Ok ...
	// return Response(500, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("DeleteConfigById method not implemented")
}

// EditConfigById - update config information
func (s *ConfigAPIService) EditConfigById(ctx context.Context, id int32, config Config) (ImplResponse, error) {
	// TODO - update EditConfigById with the required logic for this service method.
	// Add api_config_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, Config{}) or use other options such as http.Ok ...
	// return Response(200, Config{}), nil

	// TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	// return Response(400, nil),nil

	// TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	// return Response(404, nil),nil

	// TODO: Uncomment the next line to return response Response(500, {}) or use other options such as http.Ok ...
	// return Response(500, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("EditConfigById method not implemented")
}

// GetConfigByOrganizationId - get organization&#39;s config data
func (s *ConfigAPIService) GetConfigByOrganizationId(ctx context.Context, id int32) (ImplResponse, error) {
	// TODO - update GetConfigByOrganizationId with the required logic for this service method.
	// Add api_config_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, Config{}) or use other options such as http.Ok ...
	// return Response(200, Config{}), nil

	// TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	// return Response(404, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetConfigByOrganizationId method not implemented")
}

// DeleteConfigByOrganizationId - Delete organization&#39;s config data
func (s *ConfigAPIService) DeleteConfigByOrganizationId(ctx context.Context, id int32) (ImplResponse, error) {
	// TODO - update DeleteConfigByOrganizationId with the required logic for this service method.
	// Add api_config_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, {}) or use other options such as http.Ok ...
	// return Response(200, nil),nil

	// TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	// return Response(404, nil),nil

	// TODO: Uncomment the next line to return response Response(500, {}) or use other options such as http.Ok ...
	// return Response(500, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("DeleteConfigByOrganizationId method not implemented")
}

// EditConfigByOrganizationId - update organization&#39;s config information
func (s *ConfigAPIService) EditConfigByOrganizationId(ctx context.Context, id int32, config Config) (ImplResponse, error) {
	// TODO - update EditConfigByOrganizationId with the required logic for this service method.
	// Add api_config_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, Config{}) or use other options such as http.Ok ...
	// return Response(200, Config{}), nil

	// TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	// return Response(400, nil),nil

	// TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	// return Response(404, nil),nil

	// TODO: Uncomment the next line to return response Response(500, {}) or use other options such as http.Ok ...
	// return Response(500, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("EditConfigByOrganizationId method not implemented")
}
