// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Swagger loan application aggregator service - OpenAPI 3.0
 *
 * This is a sample some LoanApplication aggregator
 *
 * API version: 1.0.0
 */

package openapi

import (
	"context"
	"errors"
	"net/http"
)

// OrganizationsAPIService is a service that implements the logic for the OrganizationsAPIServicer
// This service should implement the business logic for every endpoint for the OrganizationsAPI API.
// Include any external packages or services that will be required by this service.
type OrganizationsAPIService struct {
}

// NewOrganizationsAPIService creates a default api service
func NewOrganizationsAPIService() *OrganizationsAPIService {
	return &OrganizationsAPIService{}
}

// Organizations - get all organizations
func (s *OrganizationsAPIService) Organizations(ctx context.Context) (ImplResponse, error) {
	// TODO - update Organizations with the required logic for this service method.
	// Add api_organizations_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, []Organization{}) or use other options such as http.Ok ...
	// return Response(200, []Organization{}), nil

	// TODO: Uncomment the next line to return response Response(500, {}) or use other options such as http.Ok ...
	// return Response(500, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("Organizations method not implemented")
}

// CreateOrganizationById - create new organization
func (s *OrganizationsAPIService) CreateOrganizationById(ctx context.Context, organization Organization) (ImplResponse, error) {
	// TODO - update CreateOrganizationById with the required logic for this service method.
	// Add api_organizations_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(201, Organization{}) or use other options such as http.Ok ...
	// return Response(201, Organization{}), nil

	// TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	// return Response(400, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("CreateOrganizationById method not implemented")
}

// GetOrganizationById - get organization data
func (s *OrganizationsAPIService) GetOrganizationById(ctx context.Context, id int32) (ImplResponse, error) {
	// TODO - update GetOrganizationById with the required logic for this service method.
	// Add api_organizations_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, Organization{}) or use other options such as http.Ok ...
	// return Response(200, Organization{}), nil

	// TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	// return Response(404, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetOrganizationById method not implemented")
}

// DeleteOrganizationById - delete organization
func (s *OrganizationsAPIService) DeleteOrganizationById(ctx context.Context, id int32) (ImplResponse, error) {
	// TODO - update DeleteOrganizationById with the required logic for this service method.
	// Add api_organizations_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, {}) or use other options such as http.Ok ...
	// return Response(200, nil),nil

	// TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	// return Response(400, nil),nil

	// TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	// return Response(404, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("DeleteOrganizationById method not implemented")
}

// EditOrganizationById - update organization information
func (s *OrganizationsAPIService) EditOrganizationById(ctx context.Context, id int32, organization Organization) (ImplResponse, error) {
	// TODO - update EditOrganizationById with the required logic for this service method.
	// Add api_organizations_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, Organization{}) or use other options such as http.Ok ...
	// return Response(200, Organization{}), nil

	// TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	// return Response(400, nil),nil

	// TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	// return Response(404, nil),nil

	// TODO: Uncomment the next line to return response Response(500, {}) or use other options such as http.Ok ...
	// return Response(500, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("EditOrganizationById method not implemented")
}
