// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Swagger loan application aggregator service - OpenAPI 3.0
 *
 * This is a sample some LoanApplication aggregator
 *
 * API version: 1.0.0
 */

package openapi

import (
	"context"
	"errors"
	"net/http"
)

// OrganizationsAPIService is a service that implements the logic for the OrganizationsAPIServicer
// This service should implement the business logic for every endpoint for the OrganizationsAPI API.
// Include any external packages or services that will be required by this service.
type OrganizationsAPIService struct {
}

// NewOrganizationsAPIService creates a default api service
func NewOrganizationsAPIService() *OrganizationsAPIService {
	return &OrganizationsAPIService{}
}

// Organizations - get all organizations
func (s *OrganizationsAPIService) Organizations(ctx context.Context) (ImplResponse, error) {
	// TODO - update Organizations with the required logic for this service method.
	// Add api_organizations_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, []Organization{}) or use other options such as http.Ok ...
	// return Response(200, []Organization{}), nil

	// TODO: Uncomment the next line to return response Response(500, {}) or use other options such as http.Ok ...
	// return Response(500, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("Organizations method not implemented")
}

// CreateOrganizationByUUID - create new organization
func (s *OrganizationsAPIService) CreateOrganizationByUUID(ctx context.Context, organization Organization) (ImplResponse, error) {
	// TODO - update CreateOrganizationByUUID with the required logic for this service method.
	// Add api_organizations_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(201, Organization{}) or use other options such as http.Ok ...
	// return Response(201, Organization{}), nil

	// TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	// return Response(400, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("CreateOrganizationByUUID method not implemented")
}

// GetOrganizationByUUID - get organization data
func (s *OrganizationsAPIService) GetOrganizationByUUID(ctx context.Context, uuid string) (ImplResponse, error) {
	// TODO - update GetOrganizationByUUID with the required logic for this service method.
	// Add api_organizations_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, Organization{}) or use other options such as http.Ok ...
	// return Response(200, Organization{}), nil

	// TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	// return Response(404, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetOrganizationByUUID method not implemented")
}

// DeleteOrganizationByUUID - delete organization
func (s *OrganizationsAPIService) DeleteOrganizationByUUID(ctx context.Context, uuid string) (ImplResponse, error) {
	// TODO - update DeleteOrganizationByUUID with the required logic for this service method.
	// Add api_organizations_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, {}) or use other options such as http.Ok ...
	// return Response(200, nil),nil

	// TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	// return Response(400, nil),nil

	// TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	// return Response(404, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("DeleteOrganizationByUUID method not implemented")
}

// EditOrganizationByUUID - update organization information
func (s *OrganizationsAPIService) EditOrganizationByUUID(ctx context.Context, uuid string, organization Organization) (ImplResponse, error) {
	// TODO - update EditOrganizationByUUID with the required logic for this service method.
	// Add api_organizations_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, Organization{}) or use other options such as http.Ok ...
	// return Response(200, Organization{}), nil

	// TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	// return Response(400, nil),nil

	// TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	// return Response(404, nil),nil

	// TODO: Uncomment the next line to return response Response(500, {}) or use other options such as http.Ok ...
	// return Response(500, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("EditOrganizationByUUID method not implemented")
}
