// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Swagger loan application aggregator service - OpenAPI 3.0
 *
 * This is a sample some LoanApplication aggregator
 *
 * API version: 1.0.0
 */

package openapi

import (
	"context"
	"errors"
	"net/http"
)

// LoanApplicationsAPIService is a service that implements the logic for the LoanApplicationsAPIServicer
// This service should implement the business logic for every endpoint for the LoanApplicationsAPI API.
// Include any external packages or services that will be required by this service.
type LoanApplicationsAPIService struct {
}

// NewLoanApplicationsAPIService creates a default api service
func NewLoanApplicationsAPIService() *LoanApplicationsAPIService {
	return &LoanApplicationsAPIService{}
}

// LoanApplications - get all loan applications
func (s *LoanApplicationsAPIService) LoanApplications(ctx context.Context) (ImplResponse, error) {
	// TODO - update LoanApplications with the required logic for this service method.
	// Add api_loan_applications_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, []LoanApplication{}) or use other options such as http.Ok ...
	// return Response(200, []LoanApplication{}), nil

	// TODO: Uncomment the next line to return response Response(500, {}) or use other options such as http.Ok ...
	// return Response(500, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("LoanApplications method not implemented")
}

// CreateLoanApplication - create client loan application from site
func (s *LoanApplicationsAPIService) CreateLoanApplication(ctx context.Context, loanApplication LoanApplication) (ImplResponse, error) {
	// TODO - update CreateLoanApplication with the required logic for this service method.
	// Add api_loan_applications_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(201, LoanApplication{}) or use other options such as http.Ok ...
	// return Response(201, LoanApplication{}), nil

	// TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	// return Response(400, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("CreateLoanApplication method not implemented")
}

// GetLoanApplicationById - get loan application&#39;s data
func (s *LoanApplicationsAPIService) GetLoanApplicationById(ctx context.Context, id int32) (ImplResponse, error) {
	// TODO - update GetLoanApplicationById with the required logic for this service method.
	// Add api_loan_applications_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, LoanApplication{}) or use other options such as http.Ok ...
	// return Response(200, LoanApplication{}), nil

	// TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	// return Response(404, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetLoanApplicationById method not implemented")
}

// DeleteLoanApplicationById - delete loan application
func (s *LoanApplicationsAPIService) DeleteLoanApplicationById(ctx context.Context, id int32) (ImplResponse, error) {
	// TODO - update DeleteLoanApplicationById with the required logic for this service method.
	// Add api_loan_applications_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, {}) or use other options such as http.Ok ...
	// return Response(200, nil),nil

	// TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	// return Response(404, nil),nil

	// TODO: Uncomment the next line to return response Response(500, {}) or use other options such as http.Ok ...
	// return Response(500, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("DeleteLoanApplicationById method not implemented")
}

// EditLoanApplicaitionById - update loan application information
func (s *LoanApplicationsAPIService) EditLoanApplicaitionById(ctx context.Context, id int32, loanApplication LoanApplication) (ImplResponse, error) {
	// TODO - update EditLoanApplicaitionById with the required logic for this service method.
	// Add api_loan_applications_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, LoanApplication{}) or use other options such as http.Ok ...
	// return Response(200, LoanApplication{}), nil

	// TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	// return Response(400, nil),nil

	// TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	// return Response(404, nil),nil

	// TODO: Uncomment the next line to return response Response(500, {}) or use other options such as http.Ok ...
	// return Response(500, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("EditLoanApplicaitionById method not implemented")
}
