// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Swagger loan application aggregator service - OpenAPI 3.0
 *
 * This is a sample some LoanApplication aggregator
 *
 * API version: 1.0.0
 */

package openapi

import (
	"context"
	"errors"
	"net/http"
)

// ConfigAPIService is a service that implements the logic for the ConfigAPIServicer
// This service should implement the business logic for every endpoint for the ConfigAPI API.
// Include any external packages or services that will be required by this service.
type ConfigAPIService struct {
}

// NewConfigAPIService creates a default api service
func NewConfigAPIService() *ConfigAPIService {
	return &ConfigAPIService{}
}

// GetConfigs - get configs
func (s *ConfigAPIService) GetConfigs(ctx context.Context) (ImplResponse, error) {
	// TODO - update GetConfigs with the required logic for this service method.
	// Add api_config_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, []Config{}) or use other options such as http.Ok ...
	// return Response(200, []Config{}), nil

	// TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	// return Response(404, nil),nil

	// TODO: Uncomment the next line to return response Response(500, {}) or use other options such as http.Ok ...
	// return Response(500, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetConfigs method not implemented")
}

// CreateOrganization - create new config
func (s *ConfigAPIService) CreateOrganization(ctx context.Context, config Config) (ImplResponse, error) {
	// TODO - update CreateOrganization with the required logic for this service method.
	// Add api_config_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(201, Config{}) or use other options such as http.Ok ...
	// return Response(201, Config{}), nil

	// TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	// return Response(400, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("CreateOrganization method not implemented")
}

// GetConfigByUUID - get config data
func (s *ConfigAPIService) GetConfigByUUID(ctx context.Context, uuid string) (ImplResponse, error) {
	// TODO - update GetConfigByUUID with the required logic for this service method.
	// Add api_config_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, Config{}) or use other options such as http.Ok ...
	// return Response(200, Config{}), nil

	// TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	// return Response(404, nil),nil

	// TODO: Uncomment the next line to return response Response(500, {}) or use other options such as http.Ok ...
	// return Response(500, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetConfigByUUID method not implemented")
}

// DeleteConfigByUUID - Delete config data
func (s *ConfigAPIService) DeleteConfigByUUID(ctx context.Context, uuid string) (ImplResponse, error) {
	// TODO - update DeleteConfigByUUID with the required logic for this service method.
	// Add api_config_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, {}) or use other options such as http.Ok ...
	// return Response(200, nil),nil

	// TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	// return Response(404, nil),nil

	// TODO: Uncomment the next line to return response Response(500, {}) or use other options such as http.Ok ...
	// return Response(500, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("DeleteConfigByUUID method not implemented")
}

// EditConfigByUUID - update config information
func (s *ConfigAPIService) EditConfigByUUID(ctx context.Context, uuid string, config Config) (ImplResponse, error) {
	// TODO - update EditConfigByUUID with the required logic for this service method.
	// Add api_config_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, Config{}) or use other options such as http.Ok ...
	// return Response(200, Config{}), nil

	// TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	// return Response(400, nil),nil

	// TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	// return Response(404, nil),nil

	// TODO: Uncomment the next line to return response Response(500, {}) or use other options such as http.Ok ...
	// return Response(500, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("EditConfigByUUID method not implemented")
}

// GetConfigByOrganizationUUID - get organization&#39;s config data
func (s *ConfigAPIService) GetConfigByOrganizationUUID(ctx context.Context, uuid string) (ImplResponse, error) {
	// TODO - update GetConfigByOrganizationUUID with the required logic for this service method.
	// Add api_config_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, Config{}) or use other options such as http.Ok ...
	// return Response(200, Config{}), nil

	// TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	// return Response(404, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetConfigByOrganizationUUID method not implemented")
}

// DeleteConfigByOrganizationUUID - Delete organization&#39;s config data
func (s *ConfigAPIService) DeleteConfigByOrganizationUUID(ctx context.Context, uuid string) (ImplResponse, error) {
	// TODO - update DeleteConfigByOrganizationUUID with the required logic for this service method.
	// Add api_config_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, {}) or use other options such as http.Ok ...
	// return Response(200, nil),nil

	// TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	// return Response(404, nil),nil

	// TODO: Uncomment the next line to return response Response(500, {}) or use other options such as http.Ok ...
	// return Response(500, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("DeleteConfigByOrganizationUUID method not implemented")
}

// EditConfigByOrganizationUUID - update organization&#39;s config information
func (s *ConfigAPIService) EditConfigByOrganizationUUID(ctx context.Context, uuid string, config Config) (ImplResponse, error) {
	// TODO - update EditConfigByOrganizationUUID with the required logic for this service method.
	// Add api_config_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, Config{}) or use other options such as http.Ok ...
	// return Response(200, Config{}), nil

	// TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	// return Response(400, nil),nil

	// TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	// return Response(404, nil),nil

	// TODO: Uncomment the next line to return response Response(500, {}) or use other options such as http.Ok ...
	// return Response(500, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("EditConfigByOrganizationUUID method not implemented")
}
