// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Swagger loan application aggregator service - OpenAPI 3.0
 *
 * This is a sample some LoanApplication aggregator
 *
 * API version: 1.0.0
 */

package openapi

import (
	"context"
	"errors"
	"net/http"
)

// LoanApplicationAPIService is a service that implements the logic for the LoanApplicationAPIServicer
// This service should implement the business logic for every endpoint for the LoanApplicationAPI API.
// Include any external packages or services that will be required by this service.
type LoanApplicationAPIService struct {
}

// NewLoanApplicationAPIService creates a default api service
func NewLoanApplicationAPIService() *LoanApplicationAPIService {
	return &LoanApplicationAPIService{}
}

// LoanApplication - post client loan application from site
func (s *LoanApplicationAPIService) LoanApplication(ctx context.Context, loanApplication LoanApplication) (ImplResponse, error) {
	// TODO - update LoanApplication with the required logic for this service method.
	// Add api_loan_application_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(201, LoanApplication{}) or use other options such as http.Ok ...
	// return Response(201, LoanApplication{}), nil

	// TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	// return Response(400, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("LoanApplication method not implemented")
}
