// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Swagger loan application aggregator service - OpenAPI 3.0
 *
 * This is a sample some LoanApplication aggregator
 *
 * API version: 1.0.0
 */

package openapi




type LoanApplication struct {

	Value int32 `json:"value,omitempty"`

	Phone string `json:"phone,omitempty"`

	IncomingOrganizationId int32 `json:"incoming_organization_id,omitempty"`
}

// AssertLoanApplicationRequired checks if the required fields are not zero-ed
func AssertLoanApplicationRequired(obj LoanApplication) error {
	return nil
}

// AssertLoanApplicationConstraints checks if the values respects the defined constraints
func AssertLoanApplicationConstraints(obj LoanApplication) error {
	return nil
}
