// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Swagger loan application aggregator service - OpenAPI 3.0
 *
 * This is a sample some LoanApplication aggregator
 *
 * API version: 1.0.0
 */

package openapi




type Organization struct {

	Name string `json:"name,omitempty"`
}

// AssertOrganizationRequired checks if the required fields are not zero-ed
func AssertOrganizationRequired(obj Organization) error {
	return nil
}

// AssertOrganizationConstraints checks if the values respects the defined constraints
func AssertOrganizationConstraints(obj Organization) error {
	return nil
}
