// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Swagger loan application aggregator service - OpenAPI 3.0
 *
 * This is a sample some LoanApplication aggregator
 *
 * API version: 1.0.0
 */

package openapi




type LoanApplication struct {

	Uuid string `json:"uuid,omitempty"`

	Value int32 `json:"value"`

	Phone string `json:"phone"`

	IncomingOrganizationUuid string `json:"incoming_organization_uuid"`
}

// AssertLoanApplicationRequired checks if the required fields are not zero-ed
func AssertLoanApplicationRequired(obj LoanApplication) error {
	elements := map[string]interface{}{
		"value": obj.Value,
		"phone": obj.Phone,
		"incoming_organization_uuid": obj.IncomingOrganizationUuid,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertLoanApplicationConstraints checks if the values respects the defined constraints
func AssertLoanApplicationConstraints(obj LoanApplication) error {
	return nil
}
