// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Swagger loan application aggregator service - OpenAPI 3.0
 *
 * This is a sample some LoanApplication aggregator
 *
 * API version: 1.0.0
 */

package openapi




type Config struct {

	OrganizationUuid string `json:"organization_uuid"`

	MaxLoanAmount int32 `json:"max_loan_amount"`

	NewClient bool `json:"new_client"`

	LoanAvailable bool `json:"loan_available"`

	CreatedAt string `json:"created_at,omitempty"`

	UpdatedAt string `json:"updated_at,omitempty"`

	IsAvaliable bool `json:"is_avaliable,omitempty"`
}

// AssertConfigRequired checks if the required fields are not zero-ed
func AssertConfigRequired(obj Config) error {
	elements := map[string]interface{}{
		"organization_uuid": obj.OrganizationUuid,
		"max_loan_amount": obj.MaxLoanAmount,
		"new_client": obj.NewClient,
		"loan_available": obj.LoanAvailable,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertConfigConstraints checks if the values respects the defined constraints
func AssertConfigConstraints(obj Config) error {
	return nil
}
