// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Swagger loan application aggregator service - OpenAPI 3.0
 *
 * This is a sample some LoanApplication aggregator
 *
 * API version: 1.0.0
 */

package main

import (
	openapi "github.com/donskova1ex/application_aggregator/openapi"
	"log"
	"net/http"
)

func main() {
	log.Printf("Server started")

	LoanApplicationAPIService := openapi.NewLoanApplicationAPIService()
	LoanApplicationAPIController := openapi.NewLoanApplicationAPIController(LoanApplicationAPIService)

	router := openapi.NewRouter(LoanApplicationAPIController)

	log.Fatal(http.ListenAndServe(":8080", router))
}
