openapi: 3.0.0
info:
  title: Swagger loan application aggregator service - OpenAPI 3.0
  description: |-
    This is a sample some LoanApplication aggregator
  version: 1.0.0
servers:
  - url: https://localhost:8081/api/v1
tags:
  - name: loan application aggregator
    description: API for aggregating and redirecting loan application
paths:
  /loan_applications:
    post:
      tags:
        -   loan_applications
      summary: create client loan application from site
      description: adding new client application
      operationId: CreateLoanApplication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoanApplication'
      responses:
        '201':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoanApplication'
        '400':
          description: invalid data
    get:
      tags:
        - loan_applications
      summary: get all loan applications
      description: get all loan applications
      operationId: LoanApplications
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/LoanApplication'
        '500':
          description: internal server error
  /loan_applications/{uuid}:
    get:
      tags:
        - loan_applications
      summary: get loan application's data
      description: get loan application data by uuid
      operationId: GetLoanApplicationByUUID
      parameters:
        - name: uuid
          in: path
          description: config uuid
          required: true
          schema:
            type: string
      responses:
        '200':
          description: config was found successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoanApplication'
        '404':
          description: config not found
    patch:
      tags:
        - loan_applications
      summary: update loan application information
      description: Updates loan application data by uuid
      operationId: EditLoanApplicationByUUID
      parameters:
        - name: uuid
          in: path
          description: Loan application uuid for update
          required: true
          schema:
            type: string
      requestBody:
        description: loan application object that needs to be updated
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoanApplication'
      responses:
        '200':
          description: loan application updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoanApplication'
        '400':
          description: invalid uuid or loan application data supplied
        '404':
          description: loan application not found
        '500':
          description: internal server error
    delete:
      tags:
        - loan_applications
      summary: delete loan application
      description: Delete loan application by uuid
      operationId: DeleteLoanApplicationByUUID
      parameters:
        - name: uuid
          in: path
          description: Loan application uuid for delete
          required: true
          schema:
            type: string
      responses:
        '200':
          description: loan application deleted successfully
        '404':
          description: loan application not found
        '500':
          description: Internal server error
  /organizations:
    post:
      tags:
        - organizations
      summary: create new organization
      description: adding new organization
      operationId: CreateOrganization
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Organization'
      responses:
        '201':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Organization'
        '400':
          description: invalid data
    get:
      tags:
        - organizations
      summary: get all organizations
      description: get all organizations
      operationId: Organizations
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Organization'
        '500':
          description: internal server error
  /organizations/{uuid}:
    patch:
      tags:
        - organizations
      summary: update organization information
      description: Updates organization data by uuid
      operationId: EditOrganizationByUUID
      parameters:
        - name: uuid
          in: path
          description: uuid organization for update
          required: true
          schema:
            type: string

      requestBody:
        description: organization object that needs to be updated
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Organization'
      responses:
        '200':
          description: organization updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Organization'
        '400':
          description: invalid uuid or organization data supplied
        '404':
          description: organization not found
        '500':
          description: internal server error
    delete:
      tags:
        - organizations
      summary: delete organization
      description: Delete organization by uuid
      operationId: DeleteOrganizationByUUID
      parameters:
        - name: uuid
          in: path
          description: uuid organization for delete
          required: true
          schema:
            type: string
      responses:
        '200':
          description: organization deleted successfully
        '400':
          description: invalid organization uuid
        '404':
          description: organization not found
    get:
      tags:
        - organizations
      summary: get organization data
      description: get organization data by uuid
      operationId: GetOrganizationByUUID
      parameters:
        - name: uuid
          in: path
          description: uuid organization for delete
          required: true
          schema:
            type: string
      responses:
        '200':
          description: organization was found successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Organization'
        '404':
          description: organization not found
  /configs:
    get:
      tags:
        - config
      summary: get configs
      description: get all configs
      operationId: GetConfigs
      responses:
        '200':
          description: configs was getting successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Config'
        '404':
          description: configs not found
        '500':
          description: internal server error
    post:
      tags:
        - config
      summary: create new config
      description: adding new config
      operationId: CreateConfig
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Config'
      responses:
        '201':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Config'
        '400':
          description: Invalid data
  /configs/{uuid}:
    get:
      tags:
        - config
      summary: get config data
      description: get config data by config uuid
      operationId: GetConfigByUUID
      parameters:
        - name: uuid
          in: path
          description: config uuid
          required: true
          schema:
            type: string
      responses:
        '200':
          description: config was found successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Config'
        '404':
          description: config not found
        '500':
          description: internal server error
    delete:
      tags:
        - config
      summary: Delete config data
      description: Delete config data by config uuid
      operationId: DeleteConfigByUUID
      parameters:
        - name: uuid
          in: path
          description: config uuid
          required: true
          schema:
            type: string
      responses:
        '200':
          description: config deleted successfully
        '404':
          description: config not found
        '500':
          description: internal sever error
    patch:
      tags:
        - config
      summary: update config information
      description: Updates config data by uuid
      operationId: EditConfigByUUID
      parameters:
        - name: uuid
          in: path
          description: uuid config for update
          required: true
          schema:
            type: string

      requestBody:
        description: config object that needs to be updated
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Config'
      responses:
        '200':
          description: config updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Config'
        '400':
          description: invalid uuid or config data supplied
        '404':
          description: config not found
        '500':
          description: internal server error
  /configs/organizations/{uuid}:
    get:
      tags:
        - config
      summary: get organization's config data
      description: get config data by organization uuid
      operationId: GetConfigByOrganizationUUID
      parameters:
        - name: uuid
          in: path
          description: organization uuid
          required: true
          schema:
            type: string
      responses:
        '200':
          description: config was found successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Config'
        '404':
          description: config not found
    delete:
      tags:
        - config
      summary: Delete organization's config data
      description: Delete config data by organization uuid
      operationId: DeleteConfigByOrganizationUUID
      parameters:
        - name: uuid
          in: path
          description: config uuid
          required: true
          schema:
            type: string
      responses:
        '200':
          description: config deleted successfully
        '404':
          description: config not found
        '500':
          description: internal server error
    patch:
      tags:
        - config
      summary: update organization's config information
      description: Updates config data by organization uuid
      operationId: EditConfigByOrganizationUUID
      parameters:
        - name: uuid
          in: path
          description: uuid organization for update data
          required: true
          schema:
            type: string

      requestBody:
        description: config object that needs to be updated
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Config'
      responses:
        '200':
          description: config updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Config'
        '400':
          description: invalid organization uuid or config data supplied
        '404':
          description: config not found
        '500':
          description: internal server error
components:
  schemas:
    LoanApplication:
      type: object
      required:
        - value
        - phone
        - incoming_organization_uuid
      properties:
        uuid:
          type: string
          example: 1111-1111-1111-1111-1112
        value:
          type: integer
          example: 10000
        phone:
          type: string
          example: +79994000101
        incoming_organization_uuid:
          type: string
          example: 1111-1111-1111-1111-1111
    Organization:
      type: object
      required:
        - name
      properties:
        uuid:
          type: string
          example: 1111-1111-1111-1111-1111
        name:
          type: string
          example: kassa_one
    Config:
      type: object
      required:
        - organization_uuid
        - max_loan_amount
        - new_client
        - loan_available
      properties:
        organization_uuid:
          type: string
          example: 1111-1111-1111-1111-1111
        max_loan_amount:
          type: integer
          example: 20000
        new_client:
          type: boolean
          example: true
        loan_available:
          type: boolean
          example: true
        created_at:
          type: string
          example: 2025-06-24T07:48:39.676668+05:00
        updated_at:
          type: string
          example: null
        is_avaliable:
          type: boolean
          example: true